### ISSUE TITLE
【参考までに】husky使わなくてもGit hooksいじったらもろもろできるよ！

### ISSUE THREAD

**Issue by take-cantik** [tosaken1116/nextjs-app-templates#28]
調べてみてね⭐︎

**Comment by tosaken1116** [comment]
この辺ですかね🤔
https://zenn.dev/daifukuninja/articles/2129a2d50a3a9b

今までhuskyって`.git/hooks`にスクリプト登録してるのかと思ってましたけど中身を見ると違うみたいですね
(sampleしかない)
```console
 $ ls -a .git/hooks
./                         commit-msg.sample*         pre-applypatch.sample*     pre-push.sample*           prepare-commit-msg.sample*
../                        fsmonitor-watchman.sample* pre-commit.sample*         pre-rebase.sample*         push-to-checkout.sample*
applypatch-msg.sample*     post-update.sample*        pre-merge-commit.sample*   pre-receive.sample*        update.sample*
```

けどgithooksって結局git自体で管理できませんし、プロジェクトで統一しようと思ったら別ディレクトリで作ったりと結局色々ややこしくないですかね？🤔

**Comment by take-cantik** [comment]
> githooksって結局git自体で管理できませんし

hooksに書いてるコードとほぼ同じ要領でコードで管理できるよ

**Comment by take-cantik** [comment]
git自体で管理できないってどういう意味で言ってる？
(上のコメント見当違いかも？🤔)

**Comment by take-cantik** [comment]
見てた記事の
> そこでgit config --local core.hooksPath .githooksというコマンドを使うと、そのリポジトリにおけるGit hooksの格納先を.githooksに変更することができます

ってとこら辺にやり方書いてあると思う

shでinitするときにこのコマンド叩かせたら問題なさそう👀

**Comment by tosaken1116** [comment]
shでinitするのはプロジェクトの設定そのものの初期化として使うんでプロジェクト設定者は`.git/hooks`に設定できるんですけどそれ以外のプロジェクト参加者は設定されないのでそれ用のsh用意するといいかもしれないですね(環境変数とかを全部引っ張ってくるとかも込みで)
